# Generated by Django 3.2.20 on 2023-09-20 14:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0002_auto_20230920_1406'),
        ('posts', '0003_post_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_type',
        ),
        migrations.RemoveField(
            model_name='post',
            name='views',
        ),
        migrations.AddField(
            model_name='post',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='post_documents/'),
        ),
        migrations.AddField(
            model_name='post',
            name='containers',
            field=models.ManyToManyField(to='containers.Container'),
        ),
        migrations.AddField(
            model_name='post',
            name='inspiration',
            field=models.CharField(default=django.utils.timezone.now, max_length=420),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.CharField(default=django.utils.timezone.now, max_length=42),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='post_category',
            field=models.CharField(choices=[('announcement', 'Announcement'), ('answer', 'Answer'), ('blog', 'Blog'), ('event', 'Event'), ('idea', 'Idea'), ('interview', 'Interview'), ('journal', 'Journal'), ('news', 'News'), ('review', 'Review'), ('story', 'Story'), ('tutorial', 'Tutorial'), ('question', 'Question')], default='theory', max_length=15),
        ),
        migrations.AddField(
            model_name='post',
            name='source',
            field=models.CharField(default=django.utils.timezone.now, max_length=420),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='sub_title',
            field=models.CharField(default=django.utils.timezone.now, max_length=84),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='topic',
            field=models.CharField(default=django.utils.timezone.now, max_length=42, unique=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(blank=True, max_length=2100),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='../default_post_rgq6aq', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=42, unique=True),
        ),
    ]
