# Generated by Django 3.2.20 on 2023-09-20 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_remove_post_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='images/avatar.jpg', null=True, upload_to='images/'),
        ),
    ]
