# Generated by Django 3.2.20 on 2023-09-20 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='post_images/avatar.jpg', null=True, upload_to='post_images/'),
        ),
    ]
