# Generated by Django 3.2.20 on 2023-09-20 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='post_images/tree.jpg', upload_to='post_images/'),
        ),
    ]
