# Generated by Django 3.2.20 on 2023-09-25 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='inspiration',
            field=models.CharField(max_length=840),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_category',
            field=models.CharField(choices=[('announcement', 'Announcement'), ('answer', 'Answer'), ('blog', 'Blog'), ('event', 'Event'), ('idea', 'Idea'), ('interview', 'Interview'), ('journal', 'Journal'), ('news', 'News'), ('review', 'Review'), ('story', 'Story'), ('theory', 'Theory'), ('tutorial', 'Tutorial'), ('question', 'Question')], default='theory', max_length=15),
        ),
    ]
