# Generated by Django 3.2.20 on 2023-10-20 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20231020_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='sub_title',
            field=models.CharField(max_length=84, unique=True),
        ),
    ]
