# Generated by Django 3.2.20 on 2023-09-20 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_remove_profile_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hours_per_week',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_quote',
            field=models.CharField(blank=True, max_length=84, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='website_link',
            field=models.URLField(blank=True, max_length=210, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='../default_profile_qdjgyp', null=True, upload_to='profile_images/'),
        ),
    ]
