# Generated by Django 3.2.20 on 2023-09-20 15:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20230920_0939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='website_link',
            new_name='website',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='hours_per_week',
        ),
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, 'Age cannot be negative.'), django.core.validators.MaxValueValidator(121, 'Age must be 120 or less.')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=210, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='post-images/avatar.jpg', null=True, upload_to='post-images/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
    ]
