# Generated by Django 3.2.20 on 2023-09-20 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20230920_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='profile_images/avatar.jpg', null=True, upload_to='profile_images/'),
        ),
    ]
