# Generated by Django 3.2.20 on 2023-09-20 14:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='container',
            options={'ordering': ['container_name']},
        ),
        migrations.RemoveField(
            model_name='container',
            name='description',
        ),
        migrations.RemoveField(
            model_name='container',
            name='post',
        ),
        migrations.RemoveField(
            model_name='container',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='container',
            name='container_info',
            field=models.TextField(default=django.utils.timezone.now, max_length=420),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='container',
            name='container_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=42),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='container',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
