# Generated by Django 3.2.20 on 2023-09-25 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0002_auto_20230920_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='container_info',
            field=models.TextField(max_length=210),
        ),
    ]
