# Generated by Django 3.2.20 on 2023-09-17 22:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('support_type', models.CharField(choices=[('request', 'Request Knowledge'), ('consultacy', 'Book a Consultancy'), ('support', 'Support Ticket'), ('blog', 'Blog')], default='idea', max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('support_ticket', models.IntegerField(blank=True)),
                ('image', models.ImageField(blank=True, default='../default_post_rgq6aq', upload_to='images/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
