# Generated by Django 3.2.20 on 2023-09-20 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='support',
            name='image',
        ),
        migrations.RemoveField(
            model_name='support',
            name='support_ticket',
        ),
        migrations.AddField(
            model_name='support',
            name='container_name',
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
        migrations.AddField(
            model_name='support',
            name='knowledge_name',
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
        migrations.AlterField(
            model_name='support',
            name='content',
            field=models.TextField(max_length=2100),
        ),
        migrations.AlterField(
            model_name='support',
            name='support_type',
            field=models.CharField(choices=[('request', 'Request Knowledge'), ('consultacy', 'Book a Consultancy'), ('support', 'Support Ticket')], default='support', max_length=21),
        ),
        migrations.AlterField(
            model_name='support',
            name='title',
            field=models.CharField(max_length=84),
        ),
    ]
