# Generated by Django 3.2.20 on 2023-09-25 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_alter_support_support_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='title',
            field=models.CharField(max_length=42),
        ),
    ]
