# Generated by Django 3.2.20 on 2023-10-20 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_alter_support_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support',
            name='support_type',
            field=models.CharField(choices=[('consultancy', 'Book a Consultancy'), ('feedback', 'Feedback'), ('request', 'Request Knowledge'), ('support', 'Support Ticket'), ('suggestion', 'Suggestion')], default='support', max_length=21),
        ),
    ]
